const surahmeta = {
    "Surahs": [
        { "number": 1, "name": "الفاتحة", "EngMean": "The Opening", "UrduMean": "افتتاح", "versesCount": 7 },
        { "number": 2, "name": "البقرة", "EngMean": "The Cow", "UrduMean": "گائے", "versesCount": 286 },
        { "number": 3, "name": "آل عمران", "EngMean": "Family of Imran", "UrduMean": "عمران کا گھرانہ", "versesCount": 200 },
        { "number": 4, "name": "النساء", "EngMean": "The Women", "UrduMean": "عورتیں", "versesCount": 176 },
        { "number": 5, "name": "المائدة", "EngMean": "The Table Spread", "UrduMean": "مائدہ", "versesCount": 120 },
        { "number": 6, "name": "الأنعام", "EngMean": "The Cattle", "UrduMean": "مویشی", "versesCount": 165 },
        { "number": 7, "name": "الأعراف", "EngMean": "The Heights", "UrduMean": "اونچی جگہ", "versesCount": 206 },
        { "number": 8, "name": "الأنفال", "EngMean": "The Spoils of War", "UrduMean": "مال غنیمت", "versesCount": 75 },
        { "number": 9, "name": "التوبة", "EngMean": "The Repentance", "UrduMean": "توبہ", "versesCount": 129 },
        { "number": 10, "name": "يونس", "EngMean": "Jonah", "UrduMean": "یونس", "versesCount": 109 },
        { "number": 11, "name": "هود", "EngMean": "Hud", "UrduMean": "ہود", "versesCount": 123 },
        { "number": 12, "name": "يوسف", "EngMean": "Joseph", "UrduMean": "یوسف", "versesCount": 111 },
        { "number": 13, "name": "الرعد", "EngMean": "The Thunder", "UrduMean": "گرج", "versesCount": 43 },
        { "number": 14, "name": "ابراهيم", "EngMean": "Abraham", "UrduMean": "ابراہیم", "versesCount": 52 },
        { "number": 15, "name": "الحجر", "EngMean": "The Rocky Tract", "UrduMean": "پتھریلا میدان", "versesCount": 99 },
        { "number": 16, "name": "النحل", "EngMean": "The Bee", "UrduMean": "شہد کی مکھی", "versesCount": 128 },
        { "number": 17, "name": "الإسراء", "EngMean": "The Night Journey", "UrduMean": "رات کا سفر", "versesCount": 111 },
        { "number": 18, "name": "الكهف", "EngMean": "The Cave", "UrduMean": "غار", "versesCount": 110 },
        { "number": 19, "name": "مريم", "EngMean": "Mary", "UrduMean": "مریم", "versesCount": 98 },
        { "number": 20, "name": "طه", "EngMean": "Ta-Ha", "UrduMean": "طٰہٰ", "versesCount": 135 },
        { "number": 21, "name": "الأنبياء", "EngMean": "The Prophets", "UrduMean": "انبیا", "versesCount": 112 },
        { "number": 22, "name": "الحج", "EngMean": "The Pilgrimage", "UrduMean": "حج", "versesCount": 78 },
        { "number": 23, "name": "المؤمنون", "EngMean": "The Believers", "UrduMean": "مؤمنین", "versesCount": 118 },
        { "number": 24, "name": "النور", "EngMean": "The Light", "UrduMean": "روشنی", "versesCount": 64 },
        { "number": 25, "name": "الفرقان", "EngMean": "The Criterion", "UrduMean": "فرق کرنے والا", "versesCount": 77 },
        { "number": 26, "name": "الشعراء", "EngMean": "The Poets", "UrduMean": "شعرا", "versesCount": 227 },
        { "number": 27, "name": "النمل", "EngMean": "The Ant", "UrduMean": "چیونٹی", "versesCount": 93 },
        { "number": 28, "name": "القصص", "EngMean": "The Stories", "UrduMean": "قصے", "versesCount": 88 },
        { "number": 29, "name": "العنكبوت", "EngMean": "The Spider", "UrduMean": "مکڑی", "versesCount": 69 },
        { "number": 30, "name": "الروم", "EngMean": "The Romans", "UrduMean": "رومی", "versesCount": 60 },
        { "number": 31, "name": "لقمان", "EngMean": "Luqman", "UrduMean": "لقمان", "versesCount": 34 },
        { "number": 32, "name": "السجدة", "EngMean": "The Prostration", "UrduMean": "سجدہ", "versesCount": 30 },
        { "number": 33, "name": "الأحزاب", "EngMean": "The Confederates", "UrduMean": "احزاب", "versesCount": 73 },
        { "number": 34, "name": "سبإ", "EngMean": "Sheba", "UrduMean": "سبا", "versesCount": 54 },
        { "number": 35, "name": "فاطر", "EngMean": "The Originator", "UrduMean": "پیدا کرنے والا", "versesCount": 45 },
        { "number": 36, "name": "يس", "EngMean": "Ya-Sin", "UrduMean": "یٰسٓ", "versesCount": 83 },
        { "number": 37, "name": "الصافات", "EngMean": "Those who set the Ranks", "UrduMean": "صف باندھنے والے", "versesCount": 182 },
        { "number": 38, "name": "ص", "EngMean": "Sad", "UrduMean": "صٓ", "versesCount": 88 },
        { "number": 39, "name": "الزمر", "EngMean": "The Groups", "UrduMean": "گروہ", "versesCount": 75 },
        { "number": 40, "name": "غافر", "EngMean": "The Forgiver", "UrduMean": "بخشنے والا", "versesCount": 85 },
        { "number": 41, "name": "فصلت", "EngMean": "Explained in Detail", "UrduMean": "تفصیل سے بیان کی گئی", "versesCount": 54 },
        { "number": 42, "name": "الشورى", "EngMean": "The Consultation", "UrduMean": "مشورہ", "versesCount": 53 },
        { "number": 43, "name": "الزخرف", "EngMean": "The Gold Adornments", "UrduMean": "سونے کے زیورات", "versesCount": 89 },
        { "number": 44, "name": "الدخان", "EngMean": "The Smoke", "UrduMean": "دھواں", "versesCount": 59 },
        { "number": 45, "name": "الجاثية", "EngMean": "The Crouching", "UrduMean": "جھکنے والے", "versesCount": 37 },
        { "number": 46, "name": "الأحقاف", "EngMean": "The Wind-Curved Sandhills", "UrduMean": "ریت کے ٹیلے", "versesCount": 35 },
        { "number": 47, "name": "محمد", "EngMean": "Muhammad", "UrduMean": "محمد", "versesCount": 38 },
        { "number": 48, "name": "الفتح", "EngMean": "The Victory", "UrduMean": "فتح", "versesCount": 29 },
        { "number": 49, "name": "الحجرات", "EngMean": "The Rooms", "UrduMean": "حجرے", "versesCount": 18 },
        { "number": 50, "name": "ق", "EngMean": "Qaf", "UrduMean": "قٓ", "versesCount": 45 },
        { "number": 51, "name": "الذاريات", "EngMean": "The Winnowing Winds", "UrduMean": "ہوا کے جھونکے", "versesCount": 60 },
        { "number": 52, "name": "الطور", "EngMean": "The Mount", "UrduMean": "طور", "versesCount": 49 },
        { "number": 53, "name": "النجم", "EngMean": "The Star", "UrduMean": "ستارہ", "versesCount": 62 },
        { "number": 54, "name": "القمر", "EngMean": "The Moon", "UrduMean": "چاند", "versesCount": 55 },
        { "number": 55, "name": "الرحمن", "EngMean": "The Beneficent", "UrduMean": "رحمٰن", "versesCount": 78 },
        { "number": 56, "name": "الواقعة", "EngMean": "The Inevitable", "UrduMean": "واقع ہونے والی", "versesCount": 96 },
        { "number": 57, "name": "الحديد", "EngMean": "The Iron", "UrduMean": "لوہا", "versesCount": 29 },
        { "number": 58, "name": "المجادلة", "EngMean": "The Pleading Woman", "UrduMean": "بحث کرنے والی عورت", "versesCount": 22 },
        { "number": 59, "name": "الحشر", "EngMean": "The Exile", "UrduMean": "حشر", "versesCount": 24 },
        { "number": 60, "name": "الممتحنة", "EngMean": "She that is to be examined", "UrduMean": "جانچنے والی", "versesCount": 13 },
        { "number": 61, "name": "الصف", "EngMean": "The Ranks", "UrduMean": "صف", "versesCount": 14 },
        { "number": 62, "name": "الجمعة", "EngMean": "The Congregation", "UrduMean": "جمعہ", "versesCount": 11 },
        { "number": 63, "name": "المنافقون", "EngMean": "The Hypocrites", "UrduMean": "منافقین", "versesCount": 11 },
        { "number": 64, "name": "التغابن", "EngMean": "Mutual Disillusion", "UrduMean": "نقصان", "versesCount": 18 },
        { "number": 65, "name": "الطلاق", "EngMean": "The Divorce", "UrduMean": "طلاق", "versesCount": 12 },
        { "number": 66, "name": "التحريم", "EngMean": "The Prohibition", "UrduMean": "حرام کرنے والا", "versesCount": 12 },
        { "number": 67, "name": "الملك", "EngMean": "The Sovereignty", "UrduMean": "بادشاہت", "versesCount": 30 },
        { "number": 68, "name": "القلم", "EngMean": "The Pen", "UrduMean": "قلم", "versesCount": 52 },
        { "number": 69, "name": "الحاقة", "EngMean": "The Reality", "UrduMean": "یقیناً واقع ہونے والی", "versesCount": 52 },
        { "number": 70, "name": "المعارج", "EngMean": "The Ascending Stairways", "UrduMean": "چڑھنے کے زینے", "versesCount": 44 },
        { "number": 71, "name": "نوح", "EngMean": "Noah", "UrduMean": "نوح", "versesCount": 28 },
        { "number": 72, "name": "الجن", "EngMean": "The Jinn", "UrduMean": "جن", "versesCount": 28 },
        { "number": 73, "name": "المزمل", "EngMean": "The Enshrouded One", "UrduMean": "چادر اوڑھنے والا", "versesCount": 20 },
        { "number": 74, "name": "المدثر", "EngMean": "The Cloaked One", "UrduMean": "چادر لپیٹنے والا", "versesCount": 56 },
        { "number": 75, "name": "القيامة", "EngMean": "The Resurrection", "UrduMean": "قیامت", "versesCount": 40 },
        { "number": 76, "name": "الانسان", "EngMean": "Man", "UrduMean": "انسان", "versesCount": 31 },
        { "number": 77, "name": "المرسلات", "EngMean": "The Emissaries", "UrduMean": "بھیجے جانے والے", "versesCount": 50 },
        { "number": 78, "name": "النبإ", "EngMean": "The Tidings", "UrduMean": "خبر", "versesCount": 40 },
        { "number": 79, "name": "النازعات", "EngMean": "Those who drag forth", "UrduMean": "کھینچنے والے", "versesCount": 46 },
        { "number": 80, "name": "عبس", "EngMean": "He frowned", "UrduMean": "اس نے تیوری چڑھائی", "versesCount": 42 },
        { "number": 81, "name": "التكوير", "EngMean": "The Overthrowing", "UrduMean": "لپیٹ دینا", "versesCount": 29 },
        { "number": 82, "name": "الانفطار", "EngMean": "The Cleaving", "UrduMean": "پھٹنا", "versesCount": 19 },
        { "number": 83, "name": "المطففين", "EngMean": "Defrauding", "UrduMean": "ناپ تول میں کمی", "versesCount": 36 },
        { "number": 84, "name": "الانشقاق", "EngMean": "The Splitting Open", "UrduMean": "پھٹ جانا", "versesCount": 25 },
        { "number": 85, "name": "البروج", "EngMean": "The Mansions of the Stars", "UrduMean": "برج", "versesCount": 22 },
        { "number": 86, "name": "الطارق", "EngMean": "The Morning Star", "UrduMean": "چمکتا تارا", "versesCount": 17 },
        { "number": 87, "name": "الأعلى", "EngMean": "The Most High", "UrduMean": "سب سے بلند", "versesCount": 19 },
        { "number": 88, "name": "الغاشية", "EngMean": "The Overwhelming", "UrduMean": "ڈھانپ لینے والی", "versesCount": 26 },
        { "number": 89, "name": "الفجر", "EngMean": "The Dawn", "UrduMean": "صبح", "versesCount": 30 },
        { "number": 90, "name": "البلد", "EngMean": "The City", "UrduMean": "شہر", "versesCount": 20 },
        { "number": 91, "name": "الشمس", "EngMean": "The Sun", "UrduMean": "سورج", "versesCount": 15 },
        { "number": 92, "name": "الليل", "EngMean": "The Night", "UrduMean": "رات", "versesCount": 21 },
        { "number": 93, "name": "الضحى", "EngMean": "The Morning Hours", "UrduMean": "صبح کے وقت", "versesCount": 11 },
        { "number": 94, "name": "الشرح", "EngMean": "The Relief", "UrduMean": "کشادگی", "versesCount": 8 },
        { "number": 95, "name": "التين", "EngMean": "The Fig", "UrduMean": "انجیر", "versesCount": 8 },
        { "number": 96, "name": "العلق", "EngMean": "The Clot", "UrduMean": "خون کا لوتھڑا", "versesCount": 19 },
        { "number": 97, "name": "القدر", "EngMean": "The Power / Destiny", "UrduMean": "تقدیر", "versesCount": 5 },
        { "number": 98, "name": "البينة", "EngMean": "The Clear Proof", "UrduMean": "واضح دلیل", "versesCount": 8 },
        { "number": 99, "name": "الزلزلة", "EngMean": "The Earthquake", "UrduMean": "زلزلہ", "versesCount": 8 },
        { "number": 100, "name": "العاديات", "EngMean": "The Courser / Chargers", "UrduMean": "دوڑنے والے گھوڑے", "versesCount": 11 },
        { "number": 101, "name": "القارعة", "EngMean": "The Striking Calamity", "UrduMean": "کھڑکانے والی آفت", "versesCount": 11 },
        { "number": 102, "name": "التكاثر", "EngMean": "The Rivalry in World Increase", "UrduMean": "زیادتی کی حرص", "versesCount": 8 },
        { "number": 103, "name": "العصر", "EngMean": "The Time / Declining Day", "UrduMean": "زمانہ", "versesCount": 3 },
        { "number": 104, "name": "الهمزة", "EngMean": "The Slanderer", "UrduMean": "طعنہ دینے والا", "versesCount": 9 },
        { "number": 105, "name": "الفيل", "EngMean": "The Elephant", "UrduMean": "ہاتھی", "versesCount": 5 },
        { "number": 106, "name": "قريش", "EngMean": "Quraysh", "UrduMean": "قریش", "versesCount": 4 },
        { "number": 107, "name": "الماعون", "EngMean": "The Small Kindnesses", "UrduMean": "چھوٹی بھلائیاں", "versesCount": 7 },
        { "number": 108, "name": "الكوثر", "EngMean": "The Abundance", "UrduMean": "بہتات", "versesCount": 3 },
        { "number": 109, "name": "الكافرون", "EngMean": "The Disbelievers", "UrduMean": "کافر", "versesCount": 6 },
        { "number": 110, "name": "النصر", "EngMean": "The Divine Support", "UrduMean": "مدد", "versesCount": 3 },
        { "number": 111, "name": "المسد", "EngMean": "The Palm Fiber", "UrduMean": "سُکھی لکڑی", "versesCount": 5 },
        { "number": 112, "name": "الإخلاص", "EngMean": "The Sincerity", "UrduMean": "اخلاص", "versesCount": 4 },
        { "number": 113, "name": "الفلق", "EngMean": "The Daybreak", "UrduMean": "صبح", "versesCount": 5 },
        { "number": 114, "name": "الناس", "EngMean": "The Mankind", "UrduMean": "لوگ", "versesCount": 6 }
    ]
};
