const surahmeta = {
    "Surahs": [
        {"number": 1, "name": "الفاتحة", "EngMean": "The Opening", "UrduMean": "افتتاح", "versesCount": 7, "revelationPlace": "مکی", "engName": "Al-Fatiha"},
        {"number": 2, "name": "البقرة", "EngMean": "The Cow", "UrduMean": "گائے", "versesCount": 286, "revelationPlace": "مدنی", "engName": "Al-Baqarah"},
        {"number": 3, "name": "آل عمران", "EngMean": "Family of Imran", "UrduMean": "عمران کا گھرانہ", "versesCount": 200, "revelationPlace": "مدنی", "engName": "Aal-E-Imran"},
        {"number": 4, "name": "النساء", "EngMean": "The Women", "UrduMean": "عورتیں", "versesCount": 176, "revelationPlace": "مدنی", "engName": "An-Nisa"},
        {"number": 5, "name": "المائدة", "EngMean": "The Table Spread", "UrduMean": "مائدہ", "versesCount": 120, "revelationPlace": "مدنی", "engName": "Al-Ma'idah"},
        {"number": 6, "name": "الأنعام", "EngMean": "The Cattle", "UrduMean": "مویشی", "versesCount": 165, "revelationPlace": "مکی", "engName": "Al-An'am"},
        {"number": 7, "name": "الأعراف", "EngMean": "The Heights", "UrduMean": "اونچی جگہ", "versesCount": 206, "revelationPlace": "مکی", "engName": "Al-A'raf"},
        {"number": 8, "name": "الأنفال", "EngMean": "The Spoils of War", "UrduMean": "مال غنیمت", "versesCount": 75, "revelationPlace": "مدنی", "engName": "Al-Anfal"},
        {"number": 9, "name": "التوبة", "EngMean": "The Repentance", "UrduMean": "توبہ", "versesCount": 129, "revelationPlace": "مدنی", "engName": "At-Tawbah"},
        {"number": 10, "name": "يونس", "EngMean": "Jonah", "UrduMean": "یونس", "versesCount": 109, "revelationPlace": "مکی", "engName": "Yunus"},
        {"number": 11, "name": "هود", "EngMean": "Hud", "UrduMean": "ہود", "versesCount": 123, "revelationPlace": "مکی", "engName": "Hud"},
        {"number": 12, "name": "يوسف", "EngMean": "Joseph", "UrduMean": "یوسف", "versesCount": 111, "revelationPlace": "مکی", "engName": "Yusuf"},
        {"number": 13, "name": "الرعد", "EngMean": "The Thunder", "UrduMean": "گرج", "versesCount": 43, "revelationPlace": "مدنی", "engName": "Ar-Ra'd"},
        {"number": 14, "name": "ابراهيم", "EngMean": "Abraham", "UrduMean": "ابراہیم", "versesCount": 52, "revelationPlace": "مکی", "engName": "Ibrahim"},
        {"number": 15, "name": "الحجر", "EngMean": "The Rocky Tract", "UrduMean": "پتھریلا میدان", "versesCount": 99, "revelationPlace": "مکی", "engName": "Al-Hijr"},
        {"number": 16, "name": "النحل", "EngMean": "The Bee", "UrduMean": "شہد کی مکھی", "versesCount": 128, "revelationPlace": "مکی", "engName": "An-Nahl"},
        {"number": 17, "name": "الإسراء", "EngMean": "The Night Journey", "UrduMean": "رات کا سفر", "versesCount": 111, "revelationPlace": "مکی", "engName": "Al-Isra"},
        {"number": 18, "name": "الكهف", "EngMean": "The Cave", "UrduMean": "غار", "versesCount": 110, "revelationPlace": "مکی", "engName": "Al-Kahf"},
        {"number": 19, "name": "مريم", "EngMean": "Mary", "UrduMean": "مریم", "versesCount": 98, "revelationPlace": "مکی", "engName": "Maryam"},
        {"number": 20, "name": "طه", "EngMean": "Ta-Ha", "UrduMean": "طٰہٰ", "versesCount": 135, "revelationPlace": "مکی", "engName": "Taha"},
        {"number": 21, "name": "الأنبياء", "EngMean": "The Prophets", "UrduMean": "انبیا", "versesCount": 112, "revelationPlace": "مکی", "engName": "Al-Anbiya"},
        {"number": 22, "name": "الحج", "EngMean": "The Pilgrimage", "UrduMean": "حج", "versesCount": 78, "revelationPlace": "مدنی", "engName": "Al-Hajj"},
        {"number": 23, "name": "المؤمنون", "EngMean": "The Believers", "UrduMean": "مؤمنین", "versesCount": 118, "revelationPlace": "مکی", "engName": "Al-Mu'minun"},
        {"number": 24, "name": "النور", "EngMean": "The Light", "UrduMean": "روشنی", "versesCount": 64, "revelationPlace": "مدنی", "engName": "An-Nur"},
        {"number": 25, "name": "الفرقان", "EngMean": "The Criterion", "UrduMean": "فرق کرنے والا", "versesCount": 77, "revelationPlace": "مکی", "engName": "Al-Furqan"},
        {"number": 26, "name": "الشعراء", "EngMean": "The Poets", "UrduMean": "شعرا", "versesCount": 227, "revelationPlace": "مکی", "engName": "Ash-Shu'ara"},
        {"number": 27, "name": "النمل", "EngMean": "The Ant", "UrduMean": "چیونٹی", "versesCount": 93, "revelationPlace": "مکی", "engName": "An-Naml"},
        {"number": 28, "name": "القصص", "EngMean": "The Stories", "UrduMean": "قصے", "versesCount": 88, "revelationPlace": "مکی", "engName": "Al-Qasas"},
        {"number": 29, "name": "العنكبوت", "EngMean": "The Spider", "UrduMean": "مکڑی", "versesCount": 69, "revelationPlace": "مکی", "engName": "Al-Ankabut"},
        {"number": 30, "name": "الروم", "EngMean": "The Romans", "UrduMean": "رومی", "versesCount": 60, "revelationPlace": "مکی", "engName": "Ar-Rum"},
        {"number": 31, "name": "لقمان", "EngMean": "Luqman", "UrduMean": "لقمان", "versesCount": 34, "revelationPlace": "مکی", "engName": "Luqman"},
        {"number": 32, "name": "السجدة", "EngMean": "The Prostration", "UrduMean": "سجدہ", "versesCount": 30, "revelationPlace": "مکی", "engName": "As-Sajdah"},
        {"number": 33, "name": "الأحزاب", "EngMean": "The Confederates", "UrduMean": "احزاب", "versesCount": 73, "revelationPlace": "مدنی", "engName": "Al-Ahzab"},
        {"number": 34, "name": "سبإ", "EngMean": "Sheba", "UrduMean": "سبا", "versesCount": 54, "revelationPlace": "مکی", "engName": "Saba"},
        {"number": 35, "name": "فاطر", "EngMean": "The Originator", "UrduMean": "پیدا کرنے والا", "versesCount": 45, "revelationPlace": "مکی", "engName": "Fatir"},
        {"number": 36, "name": "يس", "EngMean": "Ya-Sin", "UrduMean": "یٰسٓ", "versesCount": 83, "revelationPlace": "مکی", "engName": "Ya-Sin"},
        {"number": 37, "name": "الصافات", "EngMean": "Those who set the Ranks", "UrduMean": "صف باندھنے والے", "versesCount": 182, "revelationPlace": "مکی", "engName": "As-Saffat"},
        {"number": 38, "name": "ص", "EngMean": "Sad", "UrduMean": "صٓ", "versesCount": 88, "revelationPlace": "مکی", "engName": "Sad"},
        {"number": 39, "name": "الزمر", "EngMean": "The Groups", "UrduMean": "گروہ", "versesCount": 75, "revelationPlace": "مکی", "engName": "Az-Zumar"},
        {"number": 40, "name": "غافر", "EngMean": "The Forgiver", "UrduMean": "بخشنے والا", "versesCount": 85, "revelationPlace": "مکی", "engName": "Ghafir"},
        {"number": 41, "name": "فصلت", "EngMean": "Explained in Detail", "UrduMean": "تفصیل سے بیان کی گئی", "versesCount": 54, "revelationPlace": "مکی", "engName": "Fussilat"},
        {"number": 42, "name": "الشورى", "EngMean": "The Consultation", "UrduMean": "مشورہ", "versesCount": 53, "revelationPlace": "مکی", "engName": "Ash-Shura"},
        {"number": 43, "name": "الزخرف", "EngMean": "The Gold Adornments", "UrduMean": "سونے کے زیورات", "versesCount": 89, "revelationPlace": "مکی", "engName": "Az-Zukhruf"},
        {"number": 44, "name": "الدخان", "EngMean": "The Smoke", "UrduMean": "دھواں", "versesCount": 59, "revelationPlace": "مکی", "engName": "Ad-Dukhan"},
        {"number": 45, "name": "الجاثية", "EngMean": "The Crouching", "UrduMean": "جھکنے والے", "versesCount": 37, "revelationPlace": "مکی", "engName": "Al-Jathiyah"},
        {"number": 46, "name": "الأحقاف", "EngMean": "The Wind-Curved Sandhills", "UrduMean": "ریت کے ٹیلے", "versesCount": 35, "revelationPlace": "مکی", "engName": "Al-Ahqaf"},
        {"number": 47, "name": "محمد", "EngMean": "Muhammad", "UrduMean": "محمد", "versesCount": 38, "revelationPlace": "مدنی", "engName": "Muhammad"},
        {"number": 48, "name": "الفتح", "EngMean": "The Victory", "UrduMean": "فتح", "versesCount": 29, "revelationPlace": "مدنی", "engName": "Al-Fath"},
        {"number": 49, "name": "الحجرات", "EngMean": "The Rooms", "UrduMean": "حجرے", "versesCount": 18, "revelationPlace": "مدنی", "engName": "Al-Hujurat"},
        {"number": 50, "name": "ق", "EngMean": "Qaf", "UrduMean": "قٓ", "versesCount": 45, "revelationPlace": "مکی", "engName": "Qaf"},
        {"number": 51, "name": "الذاريات", "EngMean": "The Winnowing Winds", "UrduMean": "ہوا کے جھونکے", "versesCount": 60, "revelationPlace": "مکی", "engName": "Adh-Dhariyat"},
        {"number": 52, "name": "الطور", "EngMean": "The Mount", "UrduMean": "طور", "versesCount": 49, "revelationPlace": "مکی", "engName": "At-Tur"},
        {"number": 53, "name": "النجم", "EngMean": "The Star", "UrduMean": "ستارہ", "versesCount": 62, "revelationPlace": "مکی", "engName": "An-Najm"},
        {"number": 54, "name": "القمر", "EngMean": "The Moon", "UrduMean": "چاند", "versesCount": 55, "revelationPlace": "مکی", "engName": "Al-Qamar"},
        {"number": 55, "name": "الرحمن", "EngMean": "The Beneficent", "UrduMean": "رحمٰن", "versesCount": 78, "revelationPlace": "مدنی", "engName": "Ar-Rahman"},
        {"number": 56, "name": "الواقعة", "EngMean": "The Inevitable", "UrduMean": "واقع ہونے والی", "versesCount": 96, "revelationPlace": "مکی", "engName": "Al-Waqi'ah"},
        {"number": 57, "name": "الحديد", "EngMean": "The Iron", "UrduMean": "لوہا", "versesCount": 29, "revelationPlace": "مدنی", "engName": "Al-Hadid"},
        {"number": 58, "name": "المجادلة", "EngMean": "The Pleading Woman", "UrduMean": "بحث کرنے والی عورت", "versesCount": 22, "revelationPlace": "مدنی", "engName": "Al-Mujadilah"},
        {"number": 59, "name": "الحشر", "EngMean": "The Exile", "UrduMean": "حشر", "versesCount": 24, "revelationPlace": "مدنی", "engName": "Al-Hashr"},
        {"number": 60, "name": "الممتحنة", "EngMean": "She that is to be examined", "UrduMean": "جانچنے والی", "versesCount": 13, "revelationPlace": "مدنی", "engName": "Al-Mumtahanah"},
        {"number": 61, "name": "الصف", "EngMean": "The Ranks", "UrduMean": "صف", "versesCount": 14, "revelationPlace": "مدنی", "engName": "As-Saff"},
        {"number": 62, "name": "الجمعة", "EngMean": "The Congregation", "UrduMean": "جمعہ", "versesCount": 11, "revelationPlace": "مدنی", "engName": "Al-Jumu'ah"},
        {"number": 63, "name": "المنافقون", "EngMean": "The Hypocrites", "UrduMean": "منافقین", "versesCount": 11, "revelationPlace": "مدنی", "engName": "Al-Munafiqun"},
        {"number": 64, "name": "التغابن", "EngMean": "Mutual Disillusion", "UrduMean": "نقصان", "versesCount": 18, "revelationPlace": "مدنی", "engName": "At-Taghabun"},
        {"number": 65, "name": "الطلاق", "EngMean": "The Divorce", "UrduMean": "طلاق", "versesCount": 12, "revelationPlace": "مدنی", "engName": "At-Talaq"},
        {"number": 66, "name": "التحريم", "EngMean": "The Prohibition", "UrduMean": "حرام کرنے والا", "versesCount": 12, "revelationPlace": "مدنی", "engName": "At-Tahrim"},
        {"number": 67, "name": "الملك", "EngMean": "The Sovereignty", "UrduMean": "بادشاہت", "versesCount": 30, "revelationPlace": "مکی", "engName": "Al-Mulk"},
        {"number": 68, "name": "القلم", "EngMean": "The Pen", "UrduMean": "قلم", "versesCount": 52, "revelationPlace": "مکی", "engName": "Al-Qalam"},
        {"number": 69, "name": "الحاقة", "EngMean": "The Reality", "UrduMean": "یقیناً واقع ہونے والی", "versesCount": 52, "revelationPlace": "مکی", "engName": "Al-Haqqah"},
        {"number": 70, "name": "المعارج", "EngMean": "The Ascending Stairways", "UrduMean": "چڑھنے کے زینے", "versesCount": 44, "revelationPlace": "مکی", "engName": "Al-Ma'arij"},
        {"number": 71, "name": "نوح", "EngMean": "Noah", "UrduMean": "نوح", "versesCount": 28, "revelationPlace": "مکی", "engName": "Nuh"},
        {"number": 72, "name": "الجن", "EngMean": "The Jinn", "UrduMean": "جن", "versesCount": 28, "revelationPlace": "مکی", "engName": "Al-Jinn"},
        {"number": 73, "name": "المزمل", "EngMean": "The Enshrouded One", "UrduMean": "چادر اوڑھنے والا", "versesCount": 20, "revelationPlace": "مکی", "engName": "Al-Muzzammil"},
        {"number": 74, "name": "المدثر", "EngMean": "The Cloaked One", "UrduMean": "چادر لپیٹنے والا", "versesCount": 56, "revelationPlace": "مکی", "engName": "Al-Muddaththir"},
        {"number": 75, "name": "القيامة", "EngMean": "The Resurrection", "UrduMean": "قیامت", "versesCount": 40, "revelationPlace": "مکی", "engName": "Al-Qiyamah"},
        {"number": 76, "name": "الانسان", "EngMean": "Man", "UrduMean": "انسان", "versesCount": 31, "revelationPlace": "مدنی", "engName": "Al-Insan"},
        {"number": 77, "name": "المرسلات", "EngMean": "The Emissaries", "UrduMean": "بھیجے جانے والے", "versesCount": 50, "revelationPlace": "مکی", "engName": "Al-Mursalat"},
        {"number": 78, "name": "النبإ", "EngMean": "The Tidings", "UrduMean": "خبر", "versesCount": 40, "revelationPlace": "مکی", "engName": "An-Naba"},
        {"number": 79, "name": "النازعات", "EngMean": "Those who drag forth", "UrduMean": "کھینچنے والے", "versesCount": 46, "revelationPlace": "مکی", "engName": "An-Nazi'at"},
        {"number": 80, "name": "عبس", "EngMean": "He frowned", "UrduMean": "اس نے تیوری چڑھائی", "versesCount": 42, "revelationPlace": "مکی", "engName": "Abasa"},
        {"number": 81, "name": "التكوير", "EngMean": "The Overthrowing", "UrduMean": "لپیٹ دینا", "versesCount": 29, "revelationPlace": "مکی", "engName": "At-Takwir"},
        {"number": 82, "name": "الانفطار", "EngMean": "The Cleaving", "UrduMean": "پھٹنا", "versesCount": 19, "revelationPlace": "مکی", "engName": "Al-Infitar"},
        {"number": 83, "name": "المطففين", "EngMean": "Defrauding", "UrduMean": "ناپ تول میں کمی", "versesCount": 36, "revelationPlace": "مکی", "engName": "Al-Mutaffifin"},
        {"number": 84, "name": "الانشقاق", "EngMean": "The Splitting Open", "UrduMean": "پھٹ جانا", "versesCount": 25, "revelationPlace": "مکی", "engName": "Al-Inshiqaq"},
        {"number": 85, "name": "البروج", "EngMean": "The Mansions of the Stars", "UrduMean": "برج", "versesCount": 22, "revelationPlace": "مکی", "engName": "Al-Buruj"},
        {"number": 86, "name": "الطارق", "EngMean": "The Morning Star", "UrduMean": "چمکتا تارا", "versesCount": 17, "revelationPlace": "مکی", "engName": "At-Tariq"},
        {"number": 87, "name": "الأعلى", "EngMean": "The Most High", "UrduMean": "سب سے بلند", "versesCount": 19, "revelationPlace": "مکی", "engName": "Al-A'la"},
        {"number": 88, "name": "الغاشية", "EngMean": "The Overwhelming", "UrduMean": "ڈھانپ لینے والی", "versesCount": 26, "revelationPlace": "مکی", "engName": "Al-Ghashiyah"},
        {"number": 89, "name": "الفجر", "EngMean": "The Dawn", "UrduMean": "صبح", "versesCount": 30, "revelationPlace": "مکی", "engName": "Al-Fajr"},
        {"number": 90, "name": "البلد", "EngMean": "The City", "UrduMean": "شہر", "versesCount": 20, "revelationPlace": "مکی", "engName": "Al-Balad"},
        {"number": 91, "name": "الشمس", "EngMean": "The Sun", "UrduMean": "سورج", "versesCount": 15, "revelationPlace": "مکی", "engName": "Ash-Shams"},
        {"number": 92, "name": "الليل", "EngMean": "The Night", "UrduMean": "رات", "versesCount": 21, "revelationPlace": "مکی", "engName": "Al-Lail"},
        {"number": 93, "name": "الضحى", "EngMean": "The Morning Hours", "UrduMean": "صبح کے وقت", "versesCount": 11, "revelationPlace": "مکی", "engName": "Ad-Duha"},
        {"number": 94, "name": "الشرح", "EngMean": "The Relief", "UrduMean": "کشادگی", "versesCount": 8, "revelationPlace": "مکی", "engName": "Ash-Sharh"},
        {"number": 95, "name": "التين", "EngMean": "The Fig", "UrduMean": "انجیر", "versesCount": 8, "revelationPlace": "مکی", "engName": "At-Tin"},
        {"number": 96, "name": "العلق", "EngMean": "The Clot", "UrduMean": "خون کا لوتھڑا", "versesCount": 19, "revelationPlace": "مکی", "engName": "Al-Alaq"},
        {"number": 97, "name": "القدر", "EngMean": "The Power / Destiny", "UrduMean": "تقدیر", "versesCount": 5, "revelationPlace": "مکی", "engName": "Al-Qadr"},
        {"number": 98, "name": "البينة", "EngMean": "The Clear Proof", "UrduMean": "واضح دلیل", "versesCount": 8, "revelationPlace": "مدنی", "engName": "Al-Bayyinah"},
        {"number": 99, "name": "الزلزلة", "EngMean": "The Earthquake", "UrduMean": "زلزلہ", "versesCount": 8, "revelationPlace": "مدنی", "engName": "Az-Zalzalah"},
        {"number": 100, "name": "العاديات", "EngMean": "The Courser / Chargers", "UrduMean": "دوڑنے والے گھوڑے", "versesCount": 11, "revelationPlace": "مکی", "engName": "Al-Adiyat"},
        {"number": 101, "name": "القارعة", "EngMean": "The Striking Calamity", "UrduMean": "کھڑکانے والی آفت", "versesCount": 11, "revelationPlace": "مکی", "engName": "Al-Qari'ah"},
        {"number": 102, "name": "التكاثر", "EngMean": "The Rivalry in World Increase", "UrduMean": "زیادتی کی حرص", "versesCount": 8, "revelationPlace": "مکی", "engName": "At-Takathur"},
        {"number": 103, "name": "العصر", "EngMean": "The Time / Declining Day", "UrduMean": "زمانہ", "versesCount": 3, "revelationPlace": "مکی", "engName": "Al-Asr"},
        {"number": 104, "name": "الهمزة", "EngMean": "The Slanderer", "UrduMean": "طعنہ دینے والا", "versesCount": 9, "revelationPlace": "مکی", "engName": "Al-Humazah"},
        {"number": 105, "name": "الفيل", "EngMean": "The Elephant", "UrduMean": "ہاتھی", "versesCount": 5, "revelationPlace": "مکی", "engName": "Al-Fil"},
        {"number": 106, "name": "قريش", "EngMean": "Quraysh", "UrduMean": "قریش", "versesCount": 4, "revelationPlace": "مکی", "engName": "Quraysh"},
        {"number": 107, "name": "الماعون", "EngMean": "The Small Kindnesses", "UrduMean": "چھوٹی بھلائیاں", "versesCount": 7, "revelationPlace": "مکی", "engName": "Al-Ma'un"},
        {"number": 108, "name": "الكوثر", "EngMean": "The Abundance", "UrduMean": "بہتات", "versesCount": 3, "revelationPlace": "مکی", "engName": "Al-Kawthar"},
        {"number": 109, "name": "الكافرون", "EngMean": "The Disbelievers", "UrduMean": "کافر", "versesCount": 6, "revelationPlace": "مکی", "engName": "Al-Kafirun"},
        {"number": 110, "name": "النصر", "EngMean": "The Divine Support", "UrduMean": "مدد", "versesCount": 3, "revelationPlace": "مدنی", "engName": "An-Nasr"},
        {"number": 111, "name": "المسد", "EngMean": "The Palm Fiber", "UrduMean": "سُکھی لکڑی", "versesCount": 5, "revelationPlace": "مکی", "engName": "Al-Masad"},
        {"number": 112, "name": "الإخلاص", "EngMean": "The Sincerity", "UrduMean": "اخلاص", "versesCount": 4, "revelationPlace": "مکی", "engName": "Al-Ikhlas"},
        {"number": 113, "name": "الفلق", "EngMean": "The Daybreak", "UrduMean": "صبح", "versesCount": 5, "revelationPlace": "مکی", "engName": "Al-Falaq"},
        {"number": 114, "name": "الناس", "EngMean": "The Mankind", "UrduMean": "لوگ", "versesCount": 6, "revelationPlace": "مکی", "engName": "An-Nas"}
    ]
};
